language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=postgres
script:
  - coverage run manage.py test
before_install:
    - pip install coveralls
after_success:
    -coveralls
cache: pip

notifications:
  slack: andela:AHjAfdwCGbFbv4W2ftGd6dES
