# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_check_nag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='nag',
            new_name='nag_interval',
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[(b'up', b'Up'), (b'down', b'Down'), (b'nag', b'Nag'), (b'paused', b'Paused')], default=b'new', max_length=6),
        ),
    ]
